export const RAJWADA_100_ITEMS = [
  // --- WARADI SPECIALS (1-15) ---
  { id: 1, name: "Patodi Bhaji", price: 220, cat: "Waradi", desc: "Gram flour cubes in a spicy, thin Varadi rassa." },
  { id: 2, name: "Paneer Waradi", price: 280, cat: "Waradi", desc: "Cottage cheese cooked in signature black Varadi spices." },
  { id: 3, name: "Mushroom Waradi", price: 260, cat: "Waradi", desc: "Fresh mushrooms tossed in a fiery local masala." },
  { id: 4, name: "Zunka Bhakar", price: 190, cat: "Waradi", desc: "Traditional dry pitla served with 2 Bhakri and Thecha." },
  { id: 5, name: "Tawa Besan", price: 160, cat: "Waradi", desc: "Smooth tempered gram flour curry, a village classic." },
  { id: 6, name: "Shegaon Kachori Chat", price: 120, cat: "Waradi", desc: "The famous local kachori topped with yogurt and chutneys." },
  { id: 7, name: "Varadi Patoda Masala", price: 210, cat: "Waradi", desc: "Spiced and steamed gram flour rolls in gravy." },
  { id: 8, name: "Thecha (Mirchi)", price: 50, cat: "Waradi", desc: "Spicy hand-pounded green chili and garlic condiment." },
  { id: 9, name: "Baingan Bharta Varadi", price: 180, cat: "Waradi", desc: "Smoked eggplant mash with green chilies and spring onion." },
  { id: 10, name: "Sev Bhaji Khandeshi", price: 170, cat: "Waradi", desc: "Fiery red gravy topped with thick spicy sev." },
  { id: 11, name: "Vangi Bharli", price: 190, cat: "Waradi", desc: "Small brinjals stuffed with peanut and coconut masala." },
  { id: 12, name: "Lasooni Methi", price: 185, cat: "Waradi", desc: "Fresh fenugreek leaves with a heavy garlic tempering." },
  { id: 13, name: "Pithla Bhakar", price: 160, cat: "Waradi", desc: "Traditional semi-liquid gram flour dish with Bhakri." },
  { id: 14, name: "Nagpuri Saoji Veg", price: 230, cat: "Waradi", desc: "Extremely spicy mixed veg in Saoji style gravy." },
  { id: 15, name: "Varadi Dal Tadka", price: 150, cat: "Waradi", desc: "Arhar dal tempered with Guntur chilies and garlic." },

  // --- APPETIZERS & TANDOOR (16-30) ---
  { id: 16, name: "Paneer Tandoori Platter", price: 499, cat: "Starters", desc: "Assorted platter of Tikka, Pahadi, and Malai (16 pcs)." },
  { id: 17, name: "Veg Tandoori Platter", price: 420, cat: "Starters", desc: "Mixed grilled veg, mushrooms, and seekh kebabs." },
  { id: 18, name: "Paneer Achari Tikka", price: 240, cat: "Starters", desc: "Paneer cubes marinated in tangy pickle spices." },
  { id: 19, name: "Veg Hara Bhara Kebab", price: 210, cat: "Starters", desc: "Pan-fried patties of spinach, peas, and potatoes." },
  { id: 20, name: "Cheese Corn Tikki", price: 230, cat: "Starters", desc: "Crispy hearts filled with molten cheese and corn." },
  { id: 21, name: "Mushroom Tikka", price: 220, cat: "Starters", desc: "Button mushrooms marinated in tandoori masala." },
  { id: 22, name: "Veg Seekh Kebab", price: 200, cat: "Starters", desc: "Minced vegetable skewers grilled in clay oven." },
  { id: 23, name: "Paneer Hariyali Tikka", price: 245, cat: "Starters", desc: "Cottage cheese in a fresh mint and coriander marinade." },
  { id: 24, name: "Tandoori Aloo", price: 180, cat: "Starters", desc: "Scooped potatoes filled with paneer and nuts, grilled." },
  { id: 25, name: "Paneer Malai Tikka", price: 260, cat: "Starters", desc: "Mildly spiced paneer with cream and cardamom." },
  { id: 26, name: "Veg Corn Seekh", price: 215, cat: "Starters", desc: "Golden corn and vegetable skewers." },
  { id: 27, name: "Paneer 65", price: 240, cat: "Starters", desc: "Deep-fried spicy paneer chunks, South Indian style." },
  { id: 28, name: "Crispy Veg", price: 195, cat: "Starters", desc: "Batter-fried vegetables tossed in spicy sauce." },
  { id: 29, name: "Veg Lollipop", price: 185, cat: "Starters", desc: "Vegetable mince balls on sticks, deep fried." },
  { id: 30, name: "Paneer Pahadi Tikka", price: 250, cat: "Starters", desc: "Green marinade with mountain herbs and garlic." },

  // --- PANEER MAIN COURSE (31-45) ---
  { id: 31, name: "Paneer Tikka Masala", price: 290, cat: "Paneer", desc: "Grilled paneer in a rich, spicy orange gravy." },
  { id: 32, name: "Paneer Angara", price: 280, cat: "Paneer", desc: "Smoky cottage cheese with fiery red spices." },
  { id: 33, name: "Paneer Maharaja", price: 310, cat: "Paneer", desc: "Chef's special triple-layered royal gravy." },
  { id: 34, name: "Paneer Butter Masala", price: 270, cat: "Paneer", desc: "Classic mild and buttery tomato-based gravy." },
  { id: 35, name: "Paneer Lababdar", price: 285, cat: "Paneer", desc: "Lush tomato-onion gravy with grated paneer." },
  { id: 36, name: "Shahi Paneer", price: 275, cat: "Paneer", desc: "White cashew gravy with a hint of sweetness." },
  { id: 37, name: "Kadhai Paneer", price: 265, cat: "Paneer", desc: "Tossed with bell peppers and freshly ground spices." },
  { id: 38, name: "Paneer Pasanda", price: 320, cat: "Paneer", desc: "Stuffed paneer sandwiches in a silky gravy." },
  { id: 39, name: "Matar Paneer", price: 240, cat: "Paneer", desc: "Peas and cottage cheese in a homestyle curry." },
  { id: 40, name: "Paneer Bhurji", price: 250, cat: "Paneer", desc: "Scrambled paneer with onions, tomatoes, and chilies." },
  { id: 41, name: "Paneer Handi", price: 270, cat: "Paneer", desc: "Cooked in a traditional clay pot for earthy flavor." },
  { id: 42, name: "Paneer Do Pyaza", price: 260, cat: "Paneer", desc: "Loaded with crunchy onions and mild spices." },
  { id: 43, name: "Palak Paneer", price: 250, cat: "Paneer", desc: "Spinach puree with tempered cottage cheese." },
  { id: 44, name: "Paneer Khurchan", price: 275, cat: "Paneer", desc: "Scraped paneer with capsicum and tomato juliennes." },
  { id: 45, name: "Paneer Toofani", price: 295, cat: "Paneer", desc: "Extra spicy preparation for the bold palate." },

  // --- KAJU & KOFTA SPECIALS (46-55) ---
  { id: 46, name: "Kaju Curry", price: 300, cat: "Special", desc: "Whole cashews in a rich brown gravy." },
  { id: 47, name: "Kaju Butter Masala", price: 320, cat: "Special", desc: "Roasted cashews in a creamy tomato sauce." },
  { id: 48, name: "Malai Kofta (Sweet)", price: 290, cat: "Special", desc: "Paneer balls in a white, creamy cashew gravy." },
  { id: 49, name: "Veg Nargisi Kofta", price: 280, cat: "Special", desc: "Vegetable dumplings in a spicy red gravy." },
  { id: 50, name: "Cheese Kofta", price: 310, cat: "Special", desc: "Melt-in-mouth cheese balls in golden gravy." },
  { id: 51, name: "Khoya Kaju", price: 330, cat: "Special", desc: "Sweet and rich khoya based cashew dish." },
  { id: 52, name: "Kaju Masala", price: 310, cat: "Special", desc: "Spicy and tangy cashew preparation." },
  { id: 53, name: "Shaam Savera Kofta", price: 320, cat: "Special", desc: "Spinach and paneer koftas in makhani gravy." },
  { id: 54, name: "Veg Maratha", price: 240, cat: "Special", desc: "Spicy vegetable cutlets in a Maharashtrian curry." },
  { id: 55, name: "Veg Khazana", price: 280, cat: "Special", desc: "A treasure of mixed vegetables in two gravies." },

  // --- MAIN COURSE VEGETABLE (56-70) ---
  { id: 56, name: "Veg Kolhapuri", price: 230, cat: "Main Course", desc: "Mixed veg in an extra spicy Kolhapuri red gravy." },
  { id: 57, name: "Veg Makhanwala", price: 240, cat: "Main Course", desc: "Mixed veg in a creamy, butter-rich tomato sauce." },
  { id: 58, name: "Veg Handi", price: 220, cat: "Main Course", desc: "Slow-cooked vegetables in a narrow-mouthed pot." },
  { id: 59, name: "Veg Jalfrezi", price: 210, cat: "Main Course", desc: "Stir-fried vegetables with a tangy touch." },
  { id: 60, name: "Aloo Gobi Adraki", price: 180, cat: "Main Course", desc: "Potatoes and cauliflower with ginger juliennes." },
  { id: 61, name: "Chana Masala", price: 190, cat: "Main Course", desc: "Chickpeas cooked in a spicy onion-tomato base." },
  { id: 62, name: "Baingan Bharta", price: 175, cat: "Main Course", desc: "Flame-roasted eggplant with peas and spices." },
  { id: 63, name: "Bhindi Fry", price: 185, cat: "Main Course", desc: "Crispy okra tossed with dry spices." },
  { id: 64, name: "Methi Matar Malai", price: 260, cat: "Main Course", desc: "Fenugreek and peas in a lush white cream gravy." },
  { id: 65, name: "Dum Aloo Kashmiri", price: 280, cat: "Main Course", desc: "Sweet and spicy stuffed potatoes in red gravy." },
  { id: 66, name: "Veg Bhuna Masala", price: 220, cat: "Main Course", desc: "Vegetables cooked in a thick, roasted spice gravy." },
  { id: 67, name: "Mixed Veg", price: 200, cat: "Main Course", desc: "A simple and nutritious blend of seasonal veg." },
  { id: 68, name: "Veg Patiala", price: 250, cat: "Main Course", desc: "Veg wrapped in papad and served in gravy." },
  { id: 69, name: "Veg Angara", price: 235, cat: "Main Course", desc: "A smoked vegetable dish with a spicy kick." },
  { id: 70, name: "Cheese Butter Masala", price: 310, cat: "Main Course", desc: "Amul cheese cubes in a rich makhani gravy." },

  // --- CHINESE SPECIALS (71-80) ---
  { id: 71, name: "Veg Manchurian Dry", price: 180, cat: "Chinese", desc: "Fried veg balls in a soy-garlic sauce." },
  { id: 72, name: "Paneer Chilli Gravy", price: 240, cat: "Chinese", desc: "Soft paneer tossed with capsicum and chilies." },
  { id: 73, name: "Veg Fried Rice", price: 190, cat: "Chinese", desc: "Classic stir-fried rice with finely chopped veg." },
  { id: 74, name: "Hakka Noodles", price: 180, cat: "Chinese", desc: "Non-spicy noodles with colorful vegetables." },
  { id: 75, name: "Triple Schezwan Rice", price: 280, cat: "Chinese", desc: "Rice, noodles, and manchurian gravy combo." },
  { id: 76, name: "Schezwan Noodles", price: 195, cat: "Chinese", desc: "Spicy noodles tossed in Schezwan sauce." },
  { id: 77, name: "Honey Chilli Potato", price: 170, cat: "Chinese", desc: "Sweet and spicy crispy potato fingers." },
  { id: 78, name: "Gobi Manchurian", price: 165, cat: "Chinese", desc: "Cauliflower florets in an Indo-Chinese glaze." },
  { id: 79, name: "Paneer 65 Dry", price: 230, cat: "Chinese", desc: "Crispy fried paneer with curry leaves and chili." },
  { id: 80, name: "Veg Spring Roll", price: 180, cat: "Chinese", desc: "Crispy wraps filled with seasoned vegetables." },

  // --- RICE & BREADS (81-95) ---
  { id: 81, name: "Veg Biryani", price: 260, cat: "Rice", desc: "Aromatic basmati rice with mixed vegetables." },
  { id: 82, name: "Veg Dum Biryani", price: 290, cat: "Rice", desc: "Slow-cooked in a sealed pot for maximum flavor." },
  { id: 83, name: "Jeera Rice", price: 140, cat: "Rice", desc: "Cumin tempered fragrant basmati rice." },
  { id: 84, name: "Butter Khichdi", price: 190, cat: "Rice", desc: "Comforting moong dal rice with extra ghee." },
  { id: 85, name: "Dal Khichdi Tadka", price: 210, cat: "Rice", desc: "Khichdi with an extra spicy garlic tempering." },
  { id: 86, name: "Steamed Rice", price: 120, cat: "Rice", desc: "Plain and simple fluffy basmati rice." },
  { id: 87, name: "Tandoori Roti", price: 25, cat: "Bread", desc: "Traditional clay oven baked wheat bread." },
  { id: 88, name: "Butter Naan", price: 55, cat: "Bread", desc: "Soft, leavened refined flour bread with butter." },
  { id: 89, name: "Garlic Naan", price: 70, cat: "Bread", desc: "Naan topped with minced garlic and coriander." },
  { id: 90, name: "Butter Kulcha", price: 60, cat: "Bread", desc: "Fluffy, butter-topped Punjabi bread." },
  { id: 91, name: "Aloo Paratha", price: 90, cat: "Bread", desc: "Whole wheat bread stuffed with spicy potatoes." },
  { id: 92, name: "Jowar Bhakri", price: 35, cat: "Bread", desc: "Hand-made millet flatbread, a Varadi staple." },
  { id: 93, name: "Bajra Bhakri", price: 40, cat: "Bread", desc: "Winter special healthy pearl millet flatbread." },
  { id: 94, name: "Lachha Paratha", price: 60, cat: "Bread", desc: "Multi-layered crispy wheat bread." },
  { id: 95, name: "Missi Roti", price: 50, cat: "Bread", desc: "Gram flour bread with onions and herbs." },

  // --- BEVERAGES & SOUPS (96-100) ---
  { id: 96, name: "Sweet Lassi", price: 80, cat: "Drinks", desc: "Thick, creamy yogurt drink with cardamom." },
  { id: 97, name: "Buttermilk (Taak)", price: 40, cat: "Drinks", desc: "Refreshing spiced yogurt-based drink." },
  { id: 98, name: "Mint Mojito", price: 120, cat: "Drinks", desc: "Zesty lime and fresh mint mocktail." },
  { id: 99, name: "Veg Manchow Soup", price: 130, cat: "Drinks", desc: "Spicy soup with crunchy fried noodles." },
  { id: 100, name: "Tomato Soup", price: 110, cat: "Drinks", desc: "Classic velvety cream of tomato soup." }
];